"%dev":
   quarkus:
     datasource:
       jdbc:
         url: jdbc:tracing:postgresql://localhost:5432/postgres
     jaeger:
       endpoint: http://localhost:14268/api/traces
quarkus:
  flyway:
    migrate-at-start: true
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:tracing:postgresql://postgres:5432/postgres
      driver: io.opentracing.contrib.jdbc.TracingDriver
    metrics:
      enabled: true
  smallrye-metrics:
    jaxrs:
      enabled: true

  swagger-ui:
    always-include: true

  log:
    console:
      async: true
      json: true
      enable: true
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      level: INFO
    category:
      "io.quarkus.arc.processor":
        level: DEBUG
      "io.quarkus.smallrye.jwt":
        level: DEBUG

  jaeger:
    endpoint: http://jaeger:14268/api/traces
    service-name: example
    sampler-type: const
    sampler-param: 1
  container-image:
    build: true

mp:
  jwt:
    verify:
      publickey:
        location: http://localhost:8084/auth/realms/public/protocol/openid-connect/certs
      issuer: http://localhost:8084/auth/realms/public
  openapi:
    scan:
      disable: true
  opentracing:
    server:
      operation-name-provider: http-path

injected:
    value: "Injected value"
value: "lookup value"

com:
  example:
    demo:
      client:
        Service/mp-rest/url=http://localhost:8180/data/client/service:

org:
  eclipse:
    microprofile:
      rest:
        client:
          propagateHeaders: "X-Request-Id,X-Forwarded-For,X-Forwarded-Proto"